version: '3'

services:
  go1:
    restart: always
    build:
      context: server
      args:
        ARG_SUCCESS_THRESHOLD: ${SUCCESS_THRESHOLD_1}
    networks:
      - default
  go2:
    restart: always
    build:
      context: server
      args:
        ARG_SUCCESS_THRESHOLD: ${SUCCESS_THRESHOLD_2}
    ports:
      - "3000:8080"
    networks:
      - default
  go3:
    restart: always
    build:
      context: server
      args:
        ARG_SUCCESS_THRESHOLD: ${SUCCESS_THRESHOLD_3}
    networks:
      - default
  go4:
    restart: always
    build:
      context: server
      args:
        ARG_SUCCESS_THRESHOLD: ${SUCCESS_THRESHOLD_4}
    networks:
      - default
  traefik:
    restart: always
    build:
      context: traefik
    ports:
      - "8080:80"
      - "9000:8082"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - default
  prometheus:
    build:
      context: prometheus
    ports:
      - 9001:9090
  grafana:
    restart: always
    build: 
      context: grafana
    depends_on:
      - prometheus
    ports:
      - "9002:3000"
