debug = true
logLevel = "INFO"
defaultEntryPoints = [ ]

[entryPoints]
    [entryPoints.http]
      address = ":80"
    [entryPoints.metrics]
      address = ":8081"
    [entryPoints.admin]
      address = ":8082"

[api]
  entryPoint = "admin"
  dashboard = true
  [api.statistics]
    recentErrors = 10

[ping]
  entryPoint = "admin"

[frontends]
  [frontends.good]
  backend = "good"
  entryPoints = [ "http" ]
    [frontends.good.routes]
    [frontends.good.routes.route1]
    rule = "PathPrefixStrip:/good/"
  [frontends.bad]
  backend = "bad"
  entryPoints = [ "http" ]
    [frontends.bad.routes]
    [frontends.bad.routes.route1]
    rule = "PathPrefixStrip:/bad/"
  [frontends.ugly]
  backend = "ugly"
  entryPoints = [ "http" ]
    [frontends.ugly.routes]
    [frontends.ugly.routes.route1]
    rule = "PathPrefixStrip:/ugly/"
  [frontends.fail]
  backend = "fail"
  entryPoints = [ "http" ]
    [frontends.fail.routes]
    [frontends.fail.routes.route1]
    rule = "PathPrefixStrip:/fail/"
  [frontends.prometheus]
    backend = "prometheus"
    entryPoints = [ "admin" ]
    [frontends.prometheus.routes]
      [frontends.prometheus.routes.route1]
        rule = "Path:/prometheus/{subpath:.*}"
      [frontends.prometheus.routes.route2]
        rule = "Path:/prometheus"
  [frontends.grafana]
    backend = "grafana"
    entryPoints = [ "admin" ]
    [frontends.grafana.routes]
      [frontends.grafana.routes.route1]
        rule = "Path:/grafana/{subpath:.*}"
      [frontends.grafana.routes.route2]
        rule = "Path:/grafana"

[file]
  watch = true

[backends]
  [backends.good]
    [backends.good.servers.server1]
    url = "http://go1:8080"
    weight = 1
  [backends.bad]
    [backends.bad.servers.server1]
    url = "http://go2:8080"
    weight = 1
  [backends.ugly]
    [backends.ugly.servers.server1]
    url = "http://go3:8080"
    weight = 1
  [backends.fail]
    [backends.fail.servers.server1]
    url = "http://go4:8080"
    weight = 1
  [backends.prometheus]
    [backends.prometheus.servers.server1]
    url = "http://prometheus:9090"
  [backends.grafana]
    [backends.grafana.servers.server1]
    url = "http://grafana:3000"

[metrics]
  [metrics.prometheus]
    entryPoint = "metrics"
    buckets = [0.1,0.3,1.2,5.0]
