debug = false
logLevel = "WARN"
defaultEntryPoints = [ ]

[entryPoints]
    [entryPoints.http]
      address = ":80"
    [entryPoints.admin]
      address = ":8081"

[api]
  entryPoint = "admin"
  dashboard = true

[ping]
  entryPoint = "admin"

[frontends]
  [frontends.good]
  backend = "good"
  entryPoints = [ "http" ]
    [frontends.good.routes]
    [frontends.good.routes.route1]
    rule = "PathPrefixStrip:/good/"
  [frontends.bad]
  backend = "bad"
  entryPoints = [ "http" ]
    [frontends.bad.routes]
    [frontends.bad.routes.route1]
    rule = "PathPrefixStrip:/bad/"
  [frontends.ugly]
  backend = "ugly"
  entryPoints = [ "http" ]
    [frontends.ugly.routes]
    [frontends.ugly.routes.route1]
    rule = "PathPrefixStrip:/ugly/"
  [frontends.fail]
  backend = "fail"
  entryPoints = [ "http" ]
    [frontends.fail.routes]
    [frontends.fail.routes.route1]
    rule = "PathPrefixStrip:/fail/"

[file]
  watch = true

[backends]
  [backends.good]
    [backends.good.servers.server1]
    url = "http://go1:8080"
    weight = 1
  [backends.bad]
    [backends.bad.servers.server1]
    url = "http://go2:8080"
    weight = 1
  [backends.ugly]
    [backends.ugly.servers.server1]
    url = "http://go3:8080"
    weight = 1
  [backends.fail]
    [backends.fail.servers.server1]
    url = "http://go4:8080"
    weight = 1

[metrics]
  [metrics.prometheus]
    entryPoint = "admin"
    buckets = [0.1,0.3,1.2,5.0]
